### PR TITLE
WPS 1.0 Compliance of the requests and References for Input/Output

### LINKED ISSUE #52: Store and update execute response document
Implement storeExecuteResponse and status request parameters

### PR DESCRIPTION
**Pull request by Noctalin**
Added RawOutput request
Merged with latest changes from jachym/pywps-4

### CODE REVIEW

**Comment by jachym** [comment]
@Noctalin travis fails:

for python 2.7: ImportError: No module named flask
for python 3: ImportError: No module named config

can you fix that or do you need help?

**Comment by Noctalin** [comment]
@jachym 
I started working on this yesterday as I was trying out tox again.
Modified the tox file and then I will put the new pull request up.

**Comment by Noctalin** [comment]
@jachym 
Added some commits to fix some import issues with Travis CI.
OWSlib doesn't have python 3 support yet the BoundingBox tests are being skipped in python 3.
Tests should be running correctly now.

**Comment by jachym** [comment]
Calin - should be merged by now (?)

po 4. 5. 2015 v 14:08 odesílatel Calin Ciociu <notifications@github.com>
napsal:

**Comment by jachym** [comment]
However, OWSlib was running with python3 recently? strange - thanks for the
info

čt 14. 5. 2015 v 14:31 odesílatel Jachym Cepicky <jachym.cepicky@gmail.com>
napsal:

**Pull request merged**
